include(CheckCXXCompilerFlag)

CHECK_CXX_COMPILER_FLAG(-std=gnu++11 COMPILER_SUPPORTS_GNU_CXX11)
CHECK_CXX_COMPILER_FLAG(-std=gnu++0x COMPILER_SUPPORTS_GNU_CXX0X)
if(COMPILER_SUPPORTS_GNU_CXX11)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")
elseif(COMPILER_SUPPORTS_GNU_CXX0X)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++0x")
else()
  message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no GNU C++11 support. Please use a different C++ compiler.")
endif()